### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/vendor-realtime#5]
* [ ] Use webpack + Babel
* [ ] Drop jQuery: 
      - use native promises
      - use XMLHttpRequest
      - use Object.assign
* [ ] Update `WisemblyRealTime.version` with Webpack

**Comment by guillaumepotier** [comment]
_bon chance_

**Comment by GabrielCousin** [comment]
![image](https://cloud.githubusercontent.com/assets/7649529/22824368/e5f1ff28-ef87-11e6-8a82-ff9452236182.png)
